version: '3.8'

services:
  flowise:
    image: flowiseai/flowise
    container_name: flowise
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - flowise_data:/root/.flowise
    environment:
      - PORT=3000
      - NODE_ENV=production
      - FLOWISE_USERNAME=
      - FLOWISE_PASSWORD=
    networks:
      - ai_network

  postgres:
    image: postgres:15
    container_name: postgres_n8n
    restart: unless-stopped
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_network

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=
      - N8N_BASIC_AUTH_PASSWORD=

      # Database settings
      - N8N_SECURE_COOKIE=false
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=
      - DB_POSTGRESDB_USER=
      - DB_POSTGRESDB_PASSWORD=

      # Fix WebSocket Issues
      - N8N_HOST=
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - WEBHOOK_URL=
      - N8N_PUSH_BACKEND=websocket

      # SMTP Email Configuration
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=smtp.gmail.com
      - N8N_SMTP_PORT=587
      - N8N_SMTP_USER=
      - N8N_SMTP_PASS=
      - N8N_SMTP_SENDER=
      - N8N_SMTP_SSL=false

      # Recommended settings
      - N8N_RUNNERS_ENABLED=true
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - ai_network

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_API_BASE_URL=
      - OPENAI_API_KEY=
    volumes:
      - openwebui_data:/app/backend/data
    networks:
      - ai_network

  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - ai_network

networks:
  ai_network:
    driver: bridge

volumes:
  flowise_data:
  n8n_data:
  openwebui_data:
  postgres_data:
